### ISSUE TITLE
Unable to approve item

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#42] opened 2020-09-24 16:33 UTC
I have created a test user with editor permissions.

I have added this user to an approval group, I have set the document type to use this approval group.

In essence this should allow the user to approve their own items on this specific document type, it shows on the "Tasks requiring my approval" box, however the approve and reject buttons are not visible on the item

**Comment by nathanwoulfe** [comment] 2020-09-24 19:25
Hi @AaronSadlerUK 

Couple of queries from me:
- in the workflow settings, is the flow type Explicit?
- are the buttons missing in the workflow detail overlay?

If flow type is not explicit, the user shouldn't ever see the tasks, so the issue isn't buttons missing, it's tasks appearing...

If the buttons are in the overlay, we're all good - the dashboard view only has the single button to open the overlay, regardless of user permissions/flow type. 

Will take a look though and see if I can reproduce on latest.

**Comment by AaronSadlerUK** [comment] 2020-09-24 19:31
Yes the workflow type is explicit

**Comment by AaronSadlerUK** [comment] 2020-09-24 19:37
Below are some screenshots to help:

It shows on the pending tasks box
![image](https://user-images.githubusercontent.com/9937803/94191443-6b364880-fea5-11ea-86e6-a6c905955cdb.png)

But when you click details, the approve button is missing:
![image](https://user-images.githubusercontent.com/9937803/94191536-8acd7100-fea5-11ea-8b51-051bdc9767bb.png)

As mentioned this user (as it's restricted as document type level) is added to the workflow group, so in essence should be able to approve their own items, this is the only way I could see to exclude specific document types from the workflow process.

**Comment by nathanwoulfe** [comment] 2020-09-24 19:47
Ta, that's helpful. Won't be anything major, bit of busted javascript not setting the correct buttons. 

Which version are you on?

**Comment by AaronSadlerUK** [comment] 2020-09-24 19:49
v1.3.9

**Comment by AaronSadlerUK** [comment] 2020-09-28 09:00
@nathanwoulfe Any updates on this?
It's a blocker for the client to go live, as you can appreciate having paid 900EUR they are being pushy

**Comment by nathanwoulfe** [comment] 2020-09-28 09:09
Haven't been able to reproduce on 1.4.0, buttons are all present and accounted for. 

If the node has a workflow configured that will take priority over the document type config, that may be the issue here? 

Will see too if I can add a setting for excluding doc types from workflow, that's probably a cleaner way to manage this scenario - excluding a content type would fall back to the default Umbraco permissions for those nodes, and not impact the permission inheritance. Might need to wait for a future release though rather than rushing it through.

**Comment by AaronSadlerUK** [comment] 2020-09-28 09:40
It only has an inherited workflow.
I agree excluding the documenttype from the workflow would be the best route here, as that is pretty much what I am trying to achieve.

3 document types (for the client they are course events) are to be excluded from the workflows, everything else needs approval.

I have added more screenshots to help with this

![image](https://user-images.githubusercontent.com/9937803/94416494-d4a0aa80-0176-11eb-92e8-b0cdf605bb81.png)

![image](https://user-images.githubusercontent.com/9937803/94416542-e2eec680-0176-11eb-87cc-b7e1e860be76.png)

![image](https://user-images.githubusercontent.com/9937803/94416587-f0a44c00-0176-11eb-92bd-619bf1810ed4.png)

**Comment by nathanwoulfe** [comment] 2020-09-28 09:51
I guess the benefit to keeping it in the workflow is the change history is kept in the one place, with comments against the changes. 

I'll get the buttons sorted for 1.4.0, then look at excluding types for 1.4.1/1.5.0. If you're able to bump up to the nightly and check the buttons, that would be a huge help too.

**Comment by AaronSadlerUK** [comment] 2020-09-28 09:59
I will bump the version shortly.

Thanks!

**Comment by nathanwoulfe** [comment] 2020-09-28 10:34
Will kick off a new build shortly too - just merged some additional stuff, allowing workflows to apply to publish only (falls back to default Umbraco permission for unpublish).

**Comment by AaronSadlerUK** [comment] 2020-09-28 12:58
I have installed 1.4.0-beta-000430, and the Workflow content app is broken:
![image](https://user-images.githubusercontent.com/9937803/94435123-a335d800-0192-11eb-96c2-466771e9a6e7.png)
![image](https://user-images.githubusercontent.com/9937803/94435177-afba3080-0192-11eb-973b-40dd01f3db97.png)

**Comment by nathanwoulfe** [comment] 2020-09-28 20:35
I've just now installed into a test site, didn't see this issue - possibly browser caching the old backoffice js?

Found a couple of minor things that need fixing too, gotta love an undocumented breaking change in Umbraco 😄

**Comment by nathanwoulfe** [comment] 2020-09-28 20:54
Also probably makes a difference if I update my test site to 8.7... 🤷

**Comment by nathanwoulfe** [comment] 2020-09-28 21:30
Annnnd have published a new beta - 000431 - which I'll give a proper shakedown shortly.

**Comment by AaronSadlerUK** [comment] 2020-09-29 08:50
I have installed 000432, all seems to work perfectly :)

**Comment by nathanwoulfe** [comment] 2020-09-29 09:21
Niiiiice - I'll get a release out tomorrow

**Comment by AaronSadlerUK** [comment] 2020-09-29 11:20
@nathanwoulfe Just found another problem.

If you change the template for a content item, and then request approval it triggers a 404 error

![image](https://user-images.githubusercontent.com/9937803/94552032-2c5e1500-024e-11eb-9116-77e8fb6929c3.png)

**Comment by nathanwoulfe** [comment] 2020-09-29 21:45
@AaronSadlerUK that will be because none of the content is dirty, so no variants are flagged for saving. Won't be a big deal to fix.

**Comment by AaronSadlerUK** [comment] 2020-10-01 15:46
So I have installed 0433 and I am still having the same issue where if I change the content template and press save I get a 404 error.

Also I am now unable to configure workflow in the content app, I get the following error:
![image](https://user-images.githubusercontent.com/9937803/94832239-90770980-0405-11eb-8260-23edfc728b2e.png)

I wonder if it will be easier to have a Slack call regarding these?

**Comment by nathanwoulfe** [comment] 2020-10-01 19:05
@AaronSadlerUK is this a new node? Is it multi-variant? Is the error throwing when the node loads or only when accessing the config section?

**Comment by AaronSadlerUK** [comment] 2020-10-01 19:09
All the content nodes are pre-existing, all I have done is update the plugin to the latest beta.
The tab worked fine on earlier releases.

As for the 404 again all pre-existing content.

Nothing new.

**Comment by nathanwoulfe** [comment] 2020-10-01 21:35
@AaronSadlerUK I'm able to reproduce this on a new invariant node, permissions object is missing since no permissions exist. That object should be an empty scaffold.

**Comment by nathanwoulfe** [comment] 2020-10-02 05:56
Latest beta fixes it - I was returning different config models depending on the node state, one was missing a couple of properties, hence the errors.

**Comment by AaronSadlerUK** [comment] 2020-10-02 08:12
Ah ok.

Please let me know when you have published the latest beta so I can continue testing

**Comment by nathanwoulfe** [comment] 2020-10-02 08:22
Should be available now, I pushed it a few hours ago, but seems to not be on NuGet...

**Comment by AaronSadlerUK** [comment] 2020-10-02 08:32
Strange, probably being indexed / approved.
Did you remember to click the list box?

**Comment by nathanwoulfe** [comment] 2020-10-02 08:42
Was a DevOps issue - I need to update the build to generate snupkg rather than symbols.nupkg, and what I thought was a working build (all green ticks) was actually not pushing anything to NuGet. Reverted some bits, building now.

**Comment by AaronSadlerUK** [comment] 2020-10-02 09:40
Ok got there!
For some reason I had to manually copy the files from packages and into the actual website.

I can confirm that I can now self approve
I can confirm that I can change the content template
The error no longer happens in the console

Just one improvement (If not by design, but not very user friendly)... If you self approve an item, the request publish button disappears until you refresh the page:
![image](https://user-images.githubusercontent.com/9937803/94909792-9dded300-049b-11eb-9dd1-d87cef3b6406.png)

**Comment by nathanwoulfe** [comment] 2020-10-02 23:39
Yeah, that's a bit shit - I've fixed it, building now. Buttons refresh was only happening on non-workflow content apps, but if you're on the workflow app and complete an action which changes the buttons, that wasn't being bound. Should be all good in the fresh beta.

Will poke it all a bit more over the weekend, then bundle up the 1.4.0 release. Thanks for your patience, and for helping track down these issues 👍

**Comment by nathanwoulfe** [comment] 2020-10-06 02:51
1.4.0 is out, so I'll close this issue - anything new related to this change can be a new issue.

**Closed by nathanwoulfe** 2020-10-06 02:51 UTC

**Comment by AaronSadlerUK** [comment] 2020-10-06 08:58
Perfect thanks!
