### ISSUE TITLE
Request Publish button not available after save

### ISSUE THREAD

**Issue by theotherpotter** [nathanwoulfe/Plumber-2#13] opened 2020-01-29 10:55 UTC
Using Plumber 2 v 1.1.1 and Umbraco v 8.5.1

I have a user who is able to update and request publish on nodes in the standard umbraco permissions.  When first opening a page the button drawer correctly states "Request publish" and correctly takes the user to the Workflow tab however when the page is saved the button reverts back to "Send for approval".  

If I manually navigate to the Workflow tab and back to the page content the button correctly shows "Request publish" again. 

I've tried removing the users access to request publish but that removes the ability for them to activate a workflow entirely.

**Comment by nathanwoulfe** [comment] 2020-01-29 11:39
v1.1.2 is queued now, will be up on nuget in 10 or so minutes.

Was a javascript issue, I needed to rebind the customised buttons after saving because Umbraco raises an event on save, which was causing the default buttons to rebind. Quick and easy fix, thanks for raising it 😃 

Please close this once you've confirmed the updated version fixes the bug.

**Comment by theotherpotter** [comment] 2020-01-29 14:23
Thanks for looking at this so quickly! Unfortunately I'm getting the same issue after upgrading to 1.1.2.

**Comment by nathanwoulfe** [comment] 2020-01-30 01:06
I'm blaming Nadal and Theim's Australian Open match...

Have you done the obvious ones - empty browser cache, bump client dependency?

**Closed** 2020-06-03 03:18 UTC
