### ISSUE TITLE
Wrong approval flow sequence

### ISSUE THREAD

**Issue by piotrkrajewskicn** [nathanwoulfe/Plumber-2#50] opened 2020-10-27 11:36 UTC
Hi! 

I'm new to the plugin so it might be just me but it seems like quite a clear bug to me. 

I have a page in 2 languages: English and Swedish. I created a separate approval flow for each of them, using 3 groups in total. 
The settings look like this respecitvely for the English and the Swedish versions:
![image](https://user-images.githubusercontent.com/40027605/97294708-a3d39400-184e-11eb-8d05-f18071663dc2.png)
![image](https://user-images.githubusercontent.com/40027605/97294753-b2ba4680-184e-11eb-9da6-f39d5d8f2090.png)

Looks good so far. But then something seems off when you look at permissions of the groups in Workflow tab:
![image](https://user-images.githubusercontent.com/40027605/97294889-e1d0b800-184e-11eb-9a1f-82d2d5187c6d.png)

The stages for the English version seem to be reversed. 
So now when I go to the Products page, do updates in both versions, do Multi-variant and request publish, here's the flow that appears on the English version:
![image](https://user-images.githubusercontent.com/40027605/97295180-412ec800-184f-11eb-8866-dec86f9a2668.png)

As you can see, both stages contain the same group (Global management). The Swedish version works fine (in Workflow activity I get Sweden management in stage 1 and then Global management in stage 2. 

Additionally I had a look at the Plumber request while accessing the Products page and here's the config from it, if it helps:
![image](https://user-images.githubusercontent.com/40027605/97295609-d205a380-184f-11eb-8114-05a5223561ae.png)

As mentioned, I've onyl just started working with your plugin so it might be just me doing something wrong. Let me know if you can confirm it as a bug and then I could try to supply you with more details if needed and maybe I manage to put up a list of steps to recreate it (I have just set it up on a clean Umbraco instalation though so haven't really done much to it yet)

Umbraco version: 8.9.0-rc
Plumber version: 1.4.2

Cheers!

**Comment by nathanwoulfe** [comment] 2020-10-27 19:20
Hi @piotrkrajewskicn that certainly looks like a bug - the assigned permission step in the JSON screenshot is reversed. 

Are you able to confirm if that's also the case in the database? Table name is WorkflowUserGroupPermission, there will be a row per assigned workflow permission, so for node 1057, eng management should be 0, global should be 1. That will help narrow down where the issue is happening - I'm not expecting it's happening when fetching the permissions, not when storing. 

I'll have a look at this today

**Comment by nathanwoulfe** [comment] 2020-10-27 21:32
@piotrkrajewskicn looks like the permission index isn't being updated when the items are sorted in the ui - I can reproduce your issue, and resolve it by removing both groups and re-adding. I'm guessing you're seeing this happen after adding the initial config on the first variant, switching to the second, updating the default, then submitting a workflow? From what I can see, that's where the incorrect permission index is set, and not updated when reordering. Will fix and build a pre-release for you to verify.

**Comment by nathanwoulfe** [comment] 2020-10-28 03:52
And fixed in 1.4.3-beta, if you feel like updating and verifying...

**Comment by piotrkrajewskicn** [comment] 2020-10-28 07:54
Hi again, thanks for the answer!
So I updated to this version: https://www.nuget.org/packages/Plumber.Workflow/1.4.3-beta-000468 which was updated 4h ago so I assume it's the proper one.

Unfortunately now I can see another(?) bug, basically nothing happens on the click of "Request publish".
So this is the same list of step that I go through on both 1.4.2 and 1.4.3-beta-000468, in 1.4.2 I can see the bug I described above (double Global stages for Swedish version of the page) and for 1.4.3-beta-000468, nothing happens after clicking"Request publish" button (even though it's green).

1. Create a new page (in English) and save it
2. Go to workflow tab
3. Setup "Stage 1: English" -> "Stage 2: Global" in the Content approval flow and Save
4. Create the Swedish version and Save it
5. Go to the Swedish Workflow configuration
6. Remove Stage 1: English
7. Add Swedish from the dropdown and click Add
8. Drag and drop the Swedish stage to be Stage 1 and Save
9. Go to Active workflow tab and Request publish for the Swedish version

**Comment by nathanwoulfe** [comment] 2020-10-28 07:58
ah yeah, I stuffed up... left some debugging stuff in when I built, which makes the initiate workflow method return early. Will have new build up in half an hour or so. Oops.

**Comment by nathanwoulfe** [comment] 2020-10-28 08:06
@piotrkrajewskicn new beta is built and deployed, will be on NuGet in a few minutes => Plumber.Workflow.1.4.3-beta-000469

**Comment by piotrkrajewskicn** [comment] 2020-10-28 09:54
Great, now it works for me, thanks a lot!  🙌

**Comment by nathanwoulfe** [comment] 2020-10-28 10:18
Excellent, glad to hear it. I'll push out a proper release tomorrow, but the beta is completely fine to use, is exactly the same as what will be in the release.

**Closed** 2020-11-09 04:59 UTC
