### ISSUE TITLE
Umbraco.UploadField properties getting cleared on saving pending changes on implicit workflow

### ISSUE THREAD

**Issue by azdyrski** [nathanwoulfe/Plumber-2#67] opened 2021-01-25 18:49 UTC
Using latest beta plumber 2: 1.5.1-beta-000508
Umbraco v8.10.1

I have workflow setup to do implicit workflow and I am a member of the approval group

On the content node, upload a file into any Umbraco.UploadField property and hit the "Request Publish" options.  The yellow "Pending content changes will be saved automatically" seems to indicate when the issue is going to occur.  When I enter change notes and Request Publish the implicit workflow seems to do it's thing I get the publish/approval message.  However, when I reload the node it no longer has the uploaded file.  

I've not tested out every data type, but the ones I have it only seems to occur on uploads.  Lists and plain text seems fine.

When going through the standard (non implicit) workflow process, the uploaded file is preserved seems like.

Thanks!

**Comment by nathanwoulfe** [comment] 2021-01-25 22:47
Hi @azdyrski thanks for letting me know - this is fixed in the latest nightly and will be part of 1.5.1. Issue was caused by not setting the files param when automatically saving dirty content.

Build will be on nuget in around 30 minutes from the time of this comment 😄

**Closed by nathanwoulfe** 2021-01-25 22:47 UTC

**Comment by azdyrski** [comment] 2021-02-02 15:07
Forgot to leave a response but the fix worked great on my end!  Thanks a bunch.
