### ISSUE TITLE
Closing out of add member and saving group creates bad data

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#39] opened 2020-09-11 20:17 UTC
When adding members to a group, if you choose a member but then close without submitting, but still save the group, bad data is added to the database.

**To Reproduce**
1. Go to Workflow Approval Groups
2. Click on a group
3. Click Members
4. Click Add
5. Search for a user
6. Select a user that is not currently a member of the group
7. Click Close
8. Click Save on the group
9. See error

![plumber-cancel-member-add-small](https://user-images.githubusercontent.com/17951/92969086-3f00dd80-f44a-11ea-9089-b168f95e363c.gif)

What happens is a record with `userId` of `0` is added

![image](https://user-images.githubusercontent.com/17951/92968687-95215100-f449-11ea-8ee0-ef94d43203d8.png)

**Expected behavior**
User should now be a member of the group

**Plumber version**
`1.3.9-beta-000415`

**Comment by nathanwoulfe** [comment] 2020-09-12 07:31
@lordscarlet I noticed this yesterday when starting some related changes for v1.4 - depending on how long that takes me to get sorted, I might need to release another patch in the interim. Issue is caused by the dialog taking the currently selected users as the selection parameter, rather than being sent a copy of the selected groups. Because it's a direct reference, selecting in the overlay updates the group model, rather than the update happening only when the overlay is submitted.

**Comment by nathanwoulfe** [comment] 2020-10-06 02:50
Resolved in 1.4.0

**Closed by nathanwoulfe** 2020-10-06 02:50 UTC
