### ISSUE TITLE
ERROR: Could not get workflows for date range

### ISSUE THREAD

**Issue by drbldgtl** [nathanwoulfe/Plumber-2#132] opened 2022-08-15 12:54 UTC
**Describe the bug**
Exception accessing Workflow dashboard following initial install.

**To Reproduce**
1. `Install-Package Plumber.Workflow` without a licence file (so should revert to trial)
2. Run project locally
3. Observe error on Workflow dashboard, "ERROR: Could not get workflows for date range"

**Expected behavior**
Dashboard should display.

**Screenshots**
![image](https://user-images.githubusercontent.com/6883719/184638080-f94af698-9f70-4a6c-8ca7-2463cacd4087.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 104.0.5112.81

**Plumber version**
10.0.1.0

**Licensed version?**
Trial

**Additional context**
Stack trace: 
```
Microsoft.Data.SqlClient.SqlException (0x80131904): 'Date' is not a recognized built-in function name.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 236
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at NPoco.Database.ExecutionHookAsync[T](Func`1 action)
   at NPoco.Database.ExecuteReaderHelperAsync(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)
   at NPoco.Database.QueryAsync[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()
   at NPoco.Database.QueryAsync[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at Plumber.Core.Repositories.Implement.Database.Fetch[T](String query, Object[] args)
   at Plumber.Core.Repositories.Implement.BaseWorkflowRepository`1.Fetch(String query, Expression`1 predicate, Object[] args)
   at Plumber.Core.Services.Implement.InstancesService.GetAllInstancesForDateRange(Nullable`1 oldest)
   at Plumber.Web.Api.InstancesController.GetRange(Int32 days)
ClientConnectionId:642ff20b-167f-4af1-8c75-f1a30419a708
Error Number:195,State:10,Class:15 
```

**Comment by nathanwoulfe** [comment] 2022-08-15 21:10
Oh that's not cool - looks very much like a SQL vs SQLite issue. Will have a look and get it patched up.

**Comment by nathanwoulfe** [comment] 2022-08-16 00:53
@drbldgtl 10.0.2-rc will be on NuGet shortly - if you could confirm the issue is resolved in the RC, I can schedule a patch release (need to confirm with my HQ colleagues re the preferred scheduling as we're still in the middle ground between acquisition and re-release)

**Comment by nathanwoulfe** [comment] 2022-08-19 23:43
Paging @drbldgtl...

**Comment by drbldgtl** [comment] 2022-08-22 16:17
@nathanwoulfe, the issue appears to have been resolved in the RC.
I see the following following install, and the error in the description no longer appears.
![image](https://user-images.githubusercontent.com/6883719/185969362-419cdf94-c4de-46ff-bc91-3d73bc75f64e.png)

**Comment by nathanwoulfe** [comment] 2022-09-01 00:16
Hey @drbldgtl plan is a release next Tuesday, with a couple of other minor fixes. Thanks for confirming this one.

**Closed by nathanwoulfe** 2022-09-01 00:16 UTC
