### ISSUE TITLE
No Save button in latest version

### ISSUE THREAD

**Issue by Jonroberts24Swansea** [nathanwoulfe/Plumber-2#24] opened 2020-06-18 08:22 UTC
Hi,
We have installed the latest version of Plumber on our 8.6.2 CMS and the "Save" button has disappeared. All we see is "Preview", "Save and Publish" with three extra options (see image).
Is there a way we can see the Save button again? We did touch upon this a few weeks back but it looks like there may be an issue still.
I hope this is OK :)?

Thanks for all your amazing help,
Jon

![no-save](https://user-images.githubusercontent.com/67054272/84996270-ee2c6200-b144-11ea-8b40-bf1ba00d8ae8.PNG)

**Comment by nathanwoulfe** [comment] 2020-06-19 07:49
Hi @Jonroberts24Swansea, I can't reproduce this - tried logging in as an admin and a creator, on a new page with no workflow configured, and the save button appears correctly. Similarly on pages with workflow configured.

Have the user permissions been modified? Are there any errors logged to the browser console?

**Comment by nathanwoulfe** [comment] 2020-07-19 02:14
Hi @Jonroberts24Swansea this should be resolved in 1.3.7. I still wasn't able to reproduce it, but the changes in the latest version remove a lot of my customization of the footer buttons, to only inject the new bits rather than replacing the entire view. Looks to be all good in my testing.

**Closed by nathanwoulfe** 2020-07-19 02:14 UTC
