### ISSUE TITLE
Console error when approving

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#46] opened 2020-10-06 09:25 UTC
When a user logged in as an editor clicks approve after requesting publish there is an error logged in the console:

![image](https://user-images.githubusercontent.com/9937803/95183706-40f65c00-07be-11eb-81ff-2e757d6823f9.png)

**Comment by nathanwoulfe** [comment] 2020-10-06 09:29
I noticed that earlier, ignored it because I was on latest Umbraco source and figured it was unrelated to Plumber. Possibly caused by show/hide logic on the footer buttons

**Comment by AaronSadlerUK** [comment] 2020-10-06 09:32
Possibly, This site is running on 8.6.5

**Comment by AaronSadlerUK** [comment] 2020-10-06 13:32
I can confirm this is no longer an issue in v1.4.1-beta-000455

**Comment by nathanwoulfe** [comment] 2020-10-09 04:34
Fixed in 1.4.1 🚀

**Closed by nathanwoulfe** 2020-10-09 04:34 UTC
